### PR TITLE
build: don't hardcode environments

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by ksnavely** [comment]
Do you need to add `couchapp` to [this](https://github.com/apache/couchdb-fauxton/pull/351/files#diff-35b4a816e0441e6a375cd925af50752cR102)?

**Comment by garrensmith** [comment]
@ksnavely I don't actually think so.

**Comment by garrensmith** [comment]
merged

**Comment by robertkowalski** [comment]
@ksnavely no, as these are just default values - `settings.template` is set in https://github.com/apache/couchdb-fauxton/blob/d7641f16e7a12faff896136826b43f7affb0a393/tasks/helper.js#L21

**Pull request merged**
