### PR TITLE
Style update for metadata page

### PR DESCRIPTION
**Pull request by benkeen**
The metadata page was kinda ugly, and Tim White recently made
a few suggestions to me on how to improve the page. This implements 
many of his ideas and generally smartens up the page a bit.

#### Old page
metadata-page-old

#### New page
metadata-page-new

### CODE REVIEW

**Comment by justin-mcdavid-ibm** [comment]
How about something like this (and hear me out)?

- Detailed field labels will help in understanding the metadata.
- The sub-headings don't currently provide much logical organization.
- Consistent justification (and units) should help in understanding values at a glance. And there shouldn't be massive orders of difference between actual data sizes and size on disk.
- The signature isn't going to mean anything on visual glance, so we can stick it under the copy-to-clipboard action.

metadata

**Comment by benkeen** [comment]
Cool!
- I don't mind dropping the headings at all. Not sure they added much. But the gaps between the sections seem odd now - could we remove them? It's all just info, anyway.
- wonder if `language: javascript` is useful? Is a doc ever not in JS? (cc @robertkowalski)
- I miss the horizontal rule. The page just looks a lot smarter with it, I think. We use horizontal rules elsewhere.
- The copy-to-clipboard signature is very clever :) I like it. 
- I personally don't like the right alignment of the second col. I don't find it more readable and to me it feels out of place somehow (do we do this anywhere else in the application at all?) But if you feel strongly on it, I'm game.

**Comment by justin-mcdavid-ibm** [comment]
I feel strongly about consistent alignment  (and wish it was used throughout our application, too). :)

I'd like to see spacing used to separate different types of values.  If you remove the one between purge sequence and data, I'd on board, but I think the other spaces allow you to visually group certain data types.

I accidentally covered the horizontal rule, and am completely fine with it coming back.

Thanks much, Ben.

**Comment by garrensmith** [comment]
I'm getting this error

`bundle.js:135902 Uncaught TypeError: Cannot read property 'toLocaleString' of undefined`

**Comment by benkeen** [comment]
Curious. Couldn't reproduce, but I made the code a bit more defensive.

**Comment by garrensmith** [comment]
+1 working for me now.

**Comment by benkeen** [comment]
Thanks @garrensmith. Merged as f6a1f82

**Pull request closed without merging**
