### PR TITLE
feat: replace shadow-borders with normal borders for more minimal look

### PR DESCRIPTION
**Pull request by lucidNTR**
## Overview

I know this is probably an annoying or sensible issue for fauxton, but even after a few years i feel that the half transparent huge shadows are outdated feel cluttered and don't really help communicate "professional db admin tool", most importantly they are so big that they are  a 'thing' in regard to brain parsing the interface so add overhead in usability.

This PR just replaces them with more standard borders, I really hope to not offend anyone, and i know these things are easy to result in bikeshedding, because easy things attract people to 'fix'  and hard things are never worked on but i promise i help on hard issues too in the future.

## Testing recommendations

manual test for visual changes

### CODE REVIEW

**Comment by garrensmith** [comment]
@lucidNTR this is a really nice clean up. I like it a lot. @Antonio-Maranhao and @popojargo what do you think?

**Comment by garrensmith** [comment]
Adding in a screenshot to show how this now looks

screenshot 2017-12-07 08 27 59

**Comment by popojargo** [comment]
👍  Definitely looks better

**Comment by mikerhodes** [comment]
Agree with @garrensmith and @popojargo that this is a really nice tweak.

**Comment by Antonio-Maranhao** [comment]
Agree 100%! Very nice improvement.
Good stuff @lucidNTR

**Pull request merged**
