### PR TITLE
tooling: automatically test for code style

### PR DESCRIPTION
**Pull request by robertkowalski**
Currently taking a look if our js coding guidelines are followed
is done manually during the main code review of a PR. This takes
a lot of time for the reviewer and often results in 1-2 more
iterations until the patch is landed, just taking the style issues
into account.

Additionally there are sometimes so much style issues that it
gets hard to focus on the real issues, e.g. the architecture of a
patch or the overall implementation.

This PR enables a precheck that allows to automatically detect if
our styleguide was followed. The errors can now get cleaned up
before the review, saving time of the reviewer and the submitter.
As most style issues won't appear any more in a review the review
focus will change to a discussion that is more related to the
actual implementation, probably resulting in better reviews and
overall code quality.

### CODE REVIEW

**Comment by kxepal** [comment]
I think you should add this check to travis as well and let him fail if style is violated. The same I planning to do for documentation today after fixing all the stuff that makes the linter sad. The motivation is to not bypass a stuff that will violate style guide again. You can follow guidelines by yourself, Fauxton team may follow it as well, but new contributors may easily miss some moment  not intentionally.

Here is how it works for [Apache Spark](https://github.com/apache/spark/pull/4916#issuecomment-77555917) by the way.

**Comment by garrensmith** [comment]
+1 this is great. Could you also create a jshintrc file and we can move all our jshint settings out of the grunt file.

I agree with @kxepal this should be added to travis as well.

**Comment by robertkowalski** [comment]
@kxepal @garrensmith it is covered by travis: https://github.com/robertkowalski/couchdb-fauxton/commit/4e1d0d3d5f0386b51c1fb2a79b3e451b901b7c7b#diff-35b4a816e0441e6a375cd925af50752cR515 :)

**Comment by robertkowalski** [comment]
@garrensmith will do in a separate PR - it is on my list!

**Comment by kxepal** [comment]
@robertkowalski cool! I miss that moment (:

**Comment by Madhuka** [comment]
Hi,

I am new to cocuhDB and I'm looking forward to GSOC. I too know that styling in JS is a pain. I too came across the same issue when we were releasing jaggery[1] (JS server side framework) few years ago. I like to know if there are any preferred style guides/code standards[2,3] for couchdb-fauxton. Knowing style guides/code standards will help us to understand existing code correctly and quickly at the moment. It will help writing correct code styles where automatically tests will pass. 

[1] http://jaggeryjs.org/
[2] https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml
[3]http://javascript.crockford.com/code.html

**Comment by robertkowalski** [comment]
@Madhuka yes, this basically codifies https://github.com/apache/couchdb-fauxton/blob/master/styleguide.md

**Comment by Madhuka** [comment]
@robertkowalski Thanks, It will be helpful for all the new comes. Since different styles are used in JS.

**Pull request closed without merging**
