### PR TITLE
Change the way tables are shown

### PR DESCRIPTION
**Pull request by pbrito**
Hi,
I used CouchDB for some time but this is my first pull request.
I personally don't like how views are display, so I just hack some changes for my liking.

I did run grunt, don't know how fix the error:

483 passing (8s)
  1 failing

  1) Index Results cellcontent formats title elements for better readability:
     expected undefined to equal '{\n  "a": 1,\n  "foo": [\n    1,\n    2,\n    3\n  ]\n}'

Paulo Brito

### CODE REVIEW

**Comment by garrensmith** [comment]
Hi @pbrito thanks for the PR. Its not quite in the direction we want to go.

We are going to be making some fixes to the table view for views.
These are the mockups [here](https://github.com/janl/couchdb-next/files/755748/Redesign.-.DBs.Docs.Indexes.and.Queries.-.Commented.pdf)

Would you be interested in helping is on those?

**Comment by pbrito** [comment]
I have some experience with react.js, so I could try to contribute to the project.
Are those mockups definitive?

**Comment by garrensmith** [comment]
They are

**Comment by garrensmith** [comment]
I'm closing this. The new Fauxton has a table, meta and json viewer that should fix the issues listed in this PR.

**Pull request closed without merging**
