### PR TITLE
Include new Ace theme in bundle

### PR DESCRIPTION
**Pull request by benkeen**
The new Ace editor theme needs to be explicitly included in the
generated bundle file.

### CODE REVIEW

**Comment by robertkowalski** [comment]
question: do we then still need `assets/js/libs/ace/theme-crimson_editor.js` that's also in that file?

**Comment by benkeen** [comment]
Good question. Yes - it's acting as a default right now. Down the road once all editor locations have been confirmed & updated, it'll be removed.

**Comment by robertkowalski** [comment]
+1

would you create a follow up ticket for the cleanup or should i create one?

**Comment by benkeen** [comment]
I'll create one right now. Thanks @robertkowalski!

**Comment by robertkowalski** [comment]
(just plus +1 if the build is green) :D

**Comment by benkeen** [comment]
Woot! :D

**Pull request merged**
