### PR TITLE
feat: change partition option to checkbox

### PR DESCRIPTION
**Pull request by garbados**
## Overview

Pursuant to https://github.com/apache/couchdb-fauxton/issues/1282 this PR changes the partition option to a checkbox.

Unfortunately I am not particularly familiar with this codebase, so this is a best-effort attempt. I was unable to test it myself.

## Related Pull Requests

- https://github.com/apache/couchdb-fauxton/issues/1282

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by brianewilkins** [comment]
It did not compile for me.
After I made the following changes it would compile for me.
```
$ diff ./app/addons/databases/components.js.orig ./app/addons/databases/components.js
324,325c324
<     this.onSetPartitioned = this.onSetPartitioned.bind(this);
<     this.onSetNotPartitioned = this.onSetNotPartitioned.bind(this);
---
>     this.onTogglePartitioned = this.onTogglePartitioned.bind(this);
393,395d391
<         <label htmlFor="partitioned-db" className='partitioned-db-label'>
<           Partitioning
<         </label>
403c399
<           <label htmlFor="partitioned-db">Partitioned</label>
---
>           <label htmlFor="partitioned-db">Partitioned Database?</label>
```

**Comment by brianewilkins** [comment]
I also found that unless these lines 358 to 365 of ./app/addons/databases/components.js are removed there is an error message when one tries to create a non-partitioned database:
```
    if (this.props.showPartitionedOption && this.state.partitionedSelected === undefined) {
      FauxtonAPI.addNotification({
        type: 'error',
        msg: 'Please select either Partitioned or Non-partitioned',
        clear: true
      });
      return;
    }
```

**Comment by garbados** [comment]
Thanks for the feedback! I have incorporated the changes you outlined.

**Comment by brianewilkins** [comment]
I think adding a gap between the "Database name" text field and the "Partitioned Database?" checkbox makes it look better.
That is, to change lines 90 to 97 of  ./app/addons/databases/assets/less/databases.less.orig from:
```
  .partitioned-db-options {
    display: flex;
    align-items: baseline;
    input {
      margin: 0px 10px 0px 0px;
    }
  }
```
to:
```
  .partitioned-db-options {
    display: flex;
    align-items: baseline;
    padding-top: 1rem;
    input {
      margin: 0px 10px 0px 0px;
    }
  }
```

**Pull request merged**
