### PR TITLE
Remove plugins that are no longer used

### PR DESCRIPTION
**Pull request by garrensmith**
Removes the old PouchDB and Plugins modules.

### CODE REVIEW

**Comment by robertkowalski** [comment]
what about https://github.com/apache/couchdb-fauxton/blob/master/app/addons/documents/resources.js#L395 ?

**Comment by robertkowalski** [comment]
btw this will close COUCHDB-2680

**Comment by michellephung** [comment]
link: https://issues.apache.org/jira/browse/COUCHDB-2680

**Comment by garrensmith** [comment]
@robertkowalski I've removed the PouchDBCollection

**Comment by robertkowalski** [comment]
+1 great!

**Comment by robertkowalski** [comment]
```
(13:33:18) [robert@tequila-work] ~/apache/couchdb-fauxton (pr/397) $ git grep pouch
.jscsrc:    "app/addons/pouchdb/pouchdb.mapreduce.js",
.jscsrc:    "app/addons/pouchdb/pouch.collate.js",
```

sent you a PR

**Comment by garrensmith** [comment]
Merged.

**Pull request closed without merging**
