### PR TITLE
Make cluster config warning applicable to CouchDB 3 as well

### PR DESCRIPTION
**Pull request by m90**
## Overview

When trying to configure a CouchDB 3 cluster in Fauxton right now, a message about CouchDB 2 will be shown, which is slightly confusing. Instead, mention that this applies to CouchDB version 2 or greater so that Fauxton remains compatible with CouchDB 2.

## Testing recommendations

Run Fauxton against a CouchDB 3 cluster and try to use in-browser configuration.

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by Antonio-Maranhao** [comment]
jenkins rebuild

**Comment by wohali** [comment]
@Antonio-Maranhao I am an idiot, that works for Jenkins, not for Travis. I forgot that Fauxton is still using Travis.

Would you like my help in moving Fauxton over to our Jenkins CI (next week)?

**Comment by Antonio-Maranhao** [comment]
Hey @wohali is there a reason to switch to Jenkins?
Travis has been working fine. The flakiness comes from browser tests with Nightwatch, so I doubt switching to Jenkins will make any difference for that.

**Comment by wohali** [comment]
@Antonio-Maranhao Just that the queue will be shorter, we have dedicated workers there and you don't have to fight with the rest of the Apache org to get a PR built.

Also, you just merged this to the wrong branch, we don't use `master` anymore. You should cherry-pick these changes to `main`.

**Comment by Antonio-Maranhao** [comment]
🤦 good catch. Thanks.

**Pull request merged**
