### PR TITLE
Fix documentation links in Fauxton

### LINKED ISSUE #955: ddocs.html HTTP 404
Visit http://localhost:5984/_utils/docs/couchapp/ddocs.html returns HTTP 404

## Expected Behavior
Show the page

## Current Behavior
HTTP 404
Not found.

## Steps to Reproduce (for bugs)
1. Edit View
2. Click the question mark

## Your Environment
* Version used: CouchDB 2.1.0
* Browser Name and version: Firefox 54
* Operating System and version (desktop or mobile): Win 10 x64 version 1703
* Link to your project: N/A

### PR DESCRIPTION
**Pull request by popojargo**
## Testing recommendations

Click on the question mark buttons in the design documents views.

## GitHub issue number
 Fixes #955 

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by popojargo** [comment]
I can't run the project locally with a clean install. I have the same issue as Jenkins...

**Comment by Antonio-Maranhao** [comment]
@popojargo the issue seems to be with `babel-eslint 8.1.2` because it works fine with v8.0.3. 
I tried updating to the latest `eslint ` and `eslint-plugin-react` but it doesn't work right off the bat. 
I'd suggest setting `"babel-eslint": "~8.0.3"` in `package.json` as a quick fix, and look into upgrading `eslint` in the future.

**Comment by popojargo** [comment]
@Antonio-Maranhao  Thanks for the tip!

**Comment by garrensmith** [comment]
+1 this looks good once the tests all pass.

**Pull request merged**
