### PR TITLE
Remove reference to $.clearForm

### PR DESCRIPTION
**Pull request by benkeen**
There's an error that appears after uploading a file. This is due
to the removal of a jQuery form lib. This PR removes the reference
to the unfound function and clears the form manually.

### CODE REVIEW

**Comment by robertkowalski** [comment]
to test this you can just add something like

```js
  .assert.attributeEquals('#_rev', 'value', '');
```

to https://github.com/benkeen/couchdb-fauxton/blob/upload-file-fix/app/addons/documents/tests/nightwatch/uploadAttachment.js#L30

**Comment by benkeen** [comment]
Good call. Will do.

**Comment by benkeen** [comment]
Thanks @robertkowalski - updated.

**Comment by robertkowalski** [comment]
+1

**Comment by benkeen** [comment]
Thanks Robert. Merged as 0c2645a

**Pull request closed without merging**
