### PR TITLE
use travis_retry in travis script

### PR DESCRIPTION
**Pull request by nolanlawson**
I noticed many of my PRs are failing, and my hunch is that they're intermittent errors (knowing how flaky Selenium tests are...). This will tell Travis to try 3 times before failing.

### CODE REVIEW

**Comment by nolanlawson** [comment]
lol of course it fails... 🙄  looks like it exceeded the max time limit. If you email Travis support, they can up your limit!

**Comment by garrensmith** [comment]
@nolanlawson just close and open this PR again to get the tests running again.

**Comment by garrensmith** [comment]
I've just emailed travis support

**Comment by nolanlawson** [comment]
@garrensmith if you're an admin, you can also restart the runs on this page: https://travis-ci.org/apache/couchdb-fauxton/builds/203189285

Or I wrote a script to automate it: https://gist.github.com/nolanlawson/7b7961b49b75e406dc7090ce6217bb5f

**Comment by garrensmith** [comment]
I don't have admin access. Because of the way it links to Apache. Committers don't get admin access. We working on changing that soon

All misspelling thanks to my iPhone.




On Sun, Feb 19, 2017 at 9:26 PM +0200, "Nolan Lawson" <notifications@github.com> wrote:












@garrensmith if you're an admin, you can also restart the runs on this page: https://travis-ci.org/apache/couchdb-fauxton/builds/203189285


Or I wrote a script to automate it: https://gist.github.com/nolanlawson/7b7961b49b75e406dc7090ce6217bb5f

**Comment by garrensmith** [comment]
+1

**Pull request closed without merging**
