### PR TITLE
Encoding issues: fix for database names and refactor of db list

### PR DESCRIPTION
**Pull request by robertkowalski**
this fix for encoded database names also includes a big refactor of the database page, pulling logic out of the views and gets rid of backbone models
- no backbone models for the db list any more
- replaces the jquery tooltips on the db list with react tooltips
- avoiding safeURLName which is broken by design
- no method calls on passed data in views any more (e.g. `{this.props.db.get('name')}` - focus on plain JSON data from flux stores

### CODE REVIEW

**Comment by robertkowalski** [comment]
note to self: clicktest db page, create new db

**Comment by robertkowalski** [comment]
this fix for encoded database names also includes a big refactor of the database page, pulling logic out of the views and getting rid of backbone models

**Comment by robertkowalski** [comment]
```
this fix for encoded database names also includes a big refactor of the database page, pulling logic out of the views and gets rid of backbone models

 - no backbone models for the db list any more
 - replaces the jquery tooltips on the db list with react tooltips
 - avoiding safeURLName which is broken by design
 - no method calls on passed data in views any more (e.g. `{this.props.db.get('name')}` - focus on plain JSON data from flux stores
```

```

**Comment by robertkowalski** [comment]
@garrensmith yes, those are existing issues in the documents section we would have to fix in the future, too. 

they are also on master.

**Comment by garrensmith** [comment]
ok then I'm +1

**Comment by garrensmith** [comment]
Need to check the new replication section before merging. Or just after.

**Comment by garrensmith** [comment]
If I click on a shared db's database I get `base.js:243 Uncaught TypeError: Cannot read property 'server' of undefined(…)`

**Comment by garrensmith** [comment]
If I click on the x icon in shared db's I get `components.react.jsx:213 Uncaught TypeError: Cannot read property 'get' of undefined(…)`

**Pull request closed without merging**
