### PR TITLE
React building blocks and navbar

### PR DESCRIPTION
**Pull request by garrensmith**
I've decided to break up #216 into two. This is the first one. It is the main react dependancies along with the main navigation bar done in React.js

### CODE REVIEW

**Comment by garrensmith** [comment]
@robertkowalski I've fixed the './base' path and replaced " with '. I haven't added a separate commit for the whitespace this time as I want to reduce the number of commits in this branch.

**Comment by robertkowalski** [comment]
@garrensmith, the travis run fails. can you fix the failing test?

**Comment by robertkowalski** [comment]
+1

maybe @benkeen can take a final look?

**Comment by michellephung** [comment]
+1

**Comment by benkeen** [comment]
Looks great. The only thing I spotted was on IE11, editing a View and clicking Save reloads the page but the Edit Index tab section has disappeared. But this is an existing bug that wasn't introduced here [N.B. ticket for it here: https://issues.apache.org/jira/browse/COUCHDB-2553].

+1 from me.

**Comment by garrensmith** [comment]
Thanks for reviewing. This is merged. Woo first React work in :+1:

**Pull request closed without merging**
