### PR TITLE
react migration: move menudropdown to react

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by benkeen** [comment]
The menu that appears on the cog icon for the databases page doesn't contain all the options as before. See screenshot (right is current master):

screen shot 2016-01-21 at 11 56 47 am

**Comment by robertkowalski** [comment]
@benkeen fixed - phew... i've seen things...

**Comment by benkeen** [comment]
looks good +1

**Comment by robertkowalski** [comment]
merged as 7fa70fd6065a29ae74d848422626a669bf7bb7a6

**Pull request closed without merging**
