### PR TITLE
Option to show only editor in CodeEditor component

### PR DESCRIPTION
**Pull request by benkeen**
This adds a `showEditorOnly` option to the <CodeEditor /> component. It prevents the extra title, beautify markup and wrapper div being included when it's not necessary. This will be needed for the React version of the full page doc editor - coming soon.

### CODE REVIEW

**Comment by robertkowalski** [comment]
unit-test missing

**Comment by benkeen** [comment]
Yeah.... I know, but sometimes things are sooo small I must question the need for the unit test. :(

**Comment by benkeen** [comment]
@robertkowalski, why do I expect your response to be: "I find your lack of faith disturbing."?

**Comment by michellephung** [comment]
+1

**Comment by garrensmith** [comment]
@benkeen a quick unit test for this would be great. Once you have a test +1

**Comment by benkeen** [comment]
No problem, added.

**Comment by garrensmith** [comment]
+1

**Pull request merged**
