### PR TITLE
Basic validation of key values entered in the Query Options panel

### PR DESCRIPTION
**Pull request by Antonio-Maranhao**
## Overview

A common (newbiew) user mistake is to forget to include double quotes in the By Keys and Between Keys fields (Query Options panel) for String values. (See https://github.com/apache/couchdb-fauxton/issues/957)
Since CouchDB accepts arbitrary JSON values as key, automatically adding the quotes is not ideal. Instead, the panel does some basic validation and displays a warning when necessary.

## Testing recommendations

- Between Keys filter
  - It should display the warning for String values without quotes (e.g.: abc)
  - It should NOT display the warning for numbers and boolean.
- By Keys filter
  - It should display the warning if the value is not enclosed in square brackets (e.g.: "abc")

## GitHub issue number

Related to https://github.com/apache/couchdb-fauxton/issues/957

### CODE REVIEW

**Comment by Antonio-Maranhao** [comment]
@willholley can you please review?

**Comment by popojargo** [comment]
@Antonio-Maranhao Why don't we automatically add the double quotes when entering a string that doesn't start and end by  {} or [] ?

For example, I enter foo and it gets formated to => `"foo"`

**Comment by Antonio-Maranhao** [comment]
@popojargo sorry for the late reply. My thinking at the time was to have a quick fix. Having the field auto-quote was a bit trickier to implement (what if the string itself has quotes, and supporting single/double quotes, etc). So I settled for showing a warning instead. 

I thought about adding the quotes behind the scenes, before sending the request, but the behavior would not be consistent. E.g. you don't use quotes for simple strings but still need them if you're using arrays. And even then if the user adds quotes themselves - do you just ignore, or are they part of the value?

Maybe I am just overthinking though. :)

**Comment by wohali** [comment]
I'd love to see this land, but the PR needs rework, and I hate seeing PRs languish this long.

Please reopen when you have a chance to get back to this.

**Pull request closed without merging**
