### PR TITLE
Detect system databases on _

### PR DESCRIPTION
**Pull request by robertkowalski**
All system databases are now prefixed by `_`, so we can remove
a lot of detection logic.

Additionally colored the warning in red.

closes COUCHDB-2607

### CODE REVIEW

**Comment by kxepal** [comment]
LGFM. Few questions:

1. Shouldn't Database mode have a property `isSystemDatabase` which encapsulates logic about how this determines?
2. Shouldn't Fauxton instead of warn about deletion system database completely prevent this action? Synthetic restriction, but will definitely save users from shooting them self in the foot.

What do you think?

**Comment by robertkowalski** [comment]
good points!

1. fixed, you are right
2. hmmm... I think we should allow it as it, I often delete my system dbs, e.g. _replicator

**Comment by kxepal** [comment]
@robertkowalski yea, killing _replicator and _users is safe, but I'm very sceptical that _dbs, _nodes and _metadata would be too. Anyway, just thinking loudly, worth to check this moment.

**Comment by robertkowalski** [comment]
@kxepal i'll ask some folks regarding that second point

**Comment by robertkowalski** [comment]
@kxepal got feedback, they say the users should be able to delete them, as sometimes replications start failing so badly that there's no way to delete it by rev or even PID and just deleting the _replicator db helps in those cases.

**Comment by kxepal** [comment]
@robertkowalski hm...that's definitely a bad use case, some sort of problem workaround. Worth to look on this problem closely. But that's beyond of this PR (:

Thanks!

**Comment by michellephung** [comment]
+1 after you change app/addons/databases/resources.js: 53 to `return (/^_/).test(this.id);`

btw, pretty neat @robertkowalski ! 
:D

**Comment by robertkowalski** [comment]
merged as 4b3b73f44349230ea8ae3a877f4c2e2a87258d9d :)

**Pull request closed without merging**
