### PR TITLE
add the cassim database to the list of internal databases

### PR DESCRIPTION
**Pull request by Poltergeist**
add the cassim database to the list of internal databases which has been
added with pull request #261.

### CODE REVIEW

**Comment by robertkowalski** [comment]
looks awesome, thank you @Poltergeist - can you format the commit message to have max 72chars per line?

maybe with a heading and a longer text explaining?

**Comment by Poltergeist** [comment]
sorry for that!

**Comment by robertkowalski** [comment]
can you please reformat it so i can land it?

**Comment by Poltergeist** [comment]
@robertkowalski fixed the commit message it should now look good.

**Comment by garrensmith** [comment]
+1

**Comment by robertkowalski** [comment]
thank you! landed as 865973ff4e15a180dc4b90954ac68c73b75239d5

**Pull request closed without merging**
