### PR TITLE
Fauxton Server for use with NPM

### PR DESCRIPTION
**Pull request by garrensmith**
This allows Fauxton to be installed via npm so that we can release newer
versions of Fauxton for users to try out.

  $ npm install fauxton -g
  $ fauxton

or see `fauxton --help` for options

### CODE REVIEW

**Comment by robertkowalski** [comment]
I found that by running the nightwatch testsuite against the server - there are probably more, but this is the first one:

```
Could not locate /Users/robert/.nvm/versions/v0.12.2/lib/node_modules/fauxton/dist/release/sdfsdf/_changes?limit=100
````

**Comment by kxepal** [comment]
A few warnings on install:
```
npm WARN engine follow@0.11.4: wanted: {"node":"0.10.x || 0.8.x"} (current: {"node":"1.8.1","npm":"2.8.3"})
npm WARN engine xmlbuilder@2.4.6: wanted: {"node":"0.8.x || 0.10.x || 0.11.x  || 1.0.x"} (current: {"node":"1.8.1","npm":"2.8.3"})
|
> fauxton@1.0.1 postinstall /home/kxepal/tmp/node_modules/fauxton
> grunt release

>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-mocha-phantomjs" not found. Is it installed?
```

But in everything else, it works perfectly with io.js 1.8.1
```

**Comment by kxepal** [comment]
Oh, no...
GET http://localhost:8000/_utils/js/ace/theme-idle_fingers.js - HTTP 404
GET http://localhost:8000/_utils/js/ace/mode-json.js - HTTP 404

**Comment by kxepal** [comment]
When you open database compaction page:
```
{"error":"ENOENT: no such file or directory, stat '/home/kxepal/tmp/node_modules/fauxton/dist/release/database/a/compact'"}
```

**Comment by kxepal** [comment]
Seems like changes feed page is broken as well:
```
Could not locate /home/kxepal/tmp/node_modules/fauxton/dist/release/a/_changes?limit=100
```

**Comment by kxepal** [comment]
Polling interval for active tasks is set as 5 seconds, but actually my Firefox 37 doing one request every 5 milliseconds.

**Comment by kxepal** [comment]
Failed to upload attachment:
```
Could not upload document: undefined
```

In console:

```
Could not locate /home/kxepal/tmp/node_modules/fauxton/dist/release/c/05155563216341bc0e69507ce06a4b9f
```

**Comment by kxepal** [comment]
Failed to clone document:
```
Could not duplicate document, reason: {"error":"ENOENT: no such file or directory, stat '/home/kxepal/tmp/node_modules/fauxton/dist/release/c/05155567753a13c8e110d96eebe348a3'"}. 
```

**Comment by kxepal** [comment]
Default map function contains very awkward code:
```
function (keys, values, rereduce) {
  if (rereduce) {
    return sum(values);
  } else {
    return values.length;
  }
}
```

**Comment by kxepal** [comment]
On view index edit page:
```
Could not locate /home/kxepal/tmp/node_modules/fauxton/dist/release/_utils/js/ace/mode-javascript.js
```

**Comment by kxepal** [comment]
Also, this page has some weird behaviour:
1. Create some view function here
2. Go to ddoc
3. Edit view function in JSON doc
4. Go back to view browsing page
5. You'll see your old function here
6. Refresh page - you'll see your actual function now
7. Refresh page - you'll see `function (keys, values, rereduce) {` default one

Also, it seems that Fauxton rejects to show all non javascript views at all.

**Comment by kxepal** [comment]
Ok, I take back my "works perfectly" words, sorry (:

**Comment by garrensmith** [comment]
@kxepal @robertkowalski I've fixed all url issues. 

@kxepal could you file a JIRA ticket for the active task bug. The Weird behaviour for the view is being fixes in #399 along with the Reduce option.

I've just pushed another version to NPM for testing.

**Comment by kxepal** [comment]
@garrensmith sure! will also check it again.

**Comment by kxepal** [comment]
@garrensmith Few more to come:
- COUCHDB-2244;
- COUCHDB-2243;
- COUCHDB-2476;
- When user tries to change own password, Fauxton forbids that requiring to be an admin;
- Bulk delete doesn't deletes all selected documents and surprisely cannot delete anything if there is only one document in database;
- File upload still doesnt works: Could not upload document: Referer header required.
- Some files are still missed:

Bonus: http://localhost:8000/_utils (:

**Comment by robertkowalski** [comment]
+1

**Comment by robertkowalski** [comment]
i think you can close this

**Comment by andreujuanc** [comment]
After installing "npm install fauxton -g". "fauxton" is not recognized. Need a hand.!

**Comment by garrensmith** [comment]
@andreujuanc could you show me your npm output when you installed it. Also which version of node and npm?

**Comment by andreujuanc** [comment]
@garrensmith  Both latest. But I had to reinstall everything because i needed the ddbb done for development today. so I'll set up everything on a different VM just for testing this. 

Also, probably was my fault, since yesterday i tried in my windows box, and worked. Maybe there was something wrong in my linux instalation.

Btw, i really like this project, but i have no time to fix. Where do I report issues?

Cheers mate.

**Comment by garrensmith** [comment]
Thats good to hear. You can submit issues here https://issues.apache.org/jira/browse/COUCHDB

**Pull request closed without merging**
