### PR TITLE
componentize the code-editor with beautfier

### PR DESCRIPTION
**Pull request by robertkowalski**
will reuse it for mango

### CODE REVIEW

**Comment by garrensmith** [comment]
This looks good. But it breaks when I try and create a new view. Also the tests are failing.

**Comment by garrensmith** [comment]
The next step is to remove the backbone view for ace editor and do it completely in React.

**Comment by garrensmith** [comment]
+1 looks great

**Comment by robertkowalski** [comment]
meregd as:

e95eec58db10c86354897f3963cf37cb2b8e96fc
18c96098b1da0a44dff93ea1dee5dfce84a6d48b

**Pull request closed without merging**
