### PR TITLE
Used brand colours so we can style them downstream

### PR DESCRIPTION
**Pull request by nickcolley**

### CODE REVIEW

**Comment by robertkowalski** [comment]
+1

**Comment by robertkowalski** [comment]
merged as 79ab3b68c73d46dc9a07d06b99829064aa93dc3b

**Comment by benkeen** [comment]
Thanks @nickcolley! All merged. Mind closing this now?

**Comment by nickcolley** [comment]
Thanks @robertkowalski @benkeen ! Keep up the good work :dancers:

**Pull request closed without merging**
