### PR TITLE
Invalid 'undefined' class in All Docs header button element

### PR DESCRIPTION
**Pull request by wadsashika**
This will remove the invalid class named undefined which appear in the All Doc header button element when landing the page.

Closes COUCHDB-2577

### CODE REVIEW

**Comment by robertkowalski** [comment]
+1

**Comment by robertkowalski** [comment]
@wadsashika can you please wrap the line endings at max 72 chars? thank you!

**Comment by robertkowalski** [comment]
background info: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by wadsashika** [comment]
@robertkowalski Thank you very much for the comment. I changed the commit message and please check it again. If there is anything to change, please let me know that.

**Comment by robertkowalski** [comment]
cool thanks! will merge asap

**Comment by robertkowalski** [comment]
merged as 7552f24e9f5cfe02e77cd61d337147de010bdd27 - thank you!

**Comment by wadsashika** [comment]
great. Thank you very much for the quick response.

**Comment by robertkowalski** [comment]
can you close the pr? we can't do it on our own. thank you :)

**Comment by wadsashika** [comment]
done :)

**Pull request closed without merging**
