### PR TITLE
footer updates

### PR DESCRIPTION
**Pull request by robertkowalski**
- add dot behind every sentence
 - add text "showing x columns if all colums are shown"
 - swap order between "show all" and amount of displayed elements
 - add border between sections
 - fix alignment of label/checkbox element

### CODE REVIEW

**Comment by benkeen** [comment]
Code looks good. Really not a fan on the `.` periods though. Looks weird and we don't add periods to one-liner text strings like this anywhere else.

**Comment by robertkowalski** [comment]
i don't have a very strong opinion regarding the periods. hmm...

**Comment by benkeen** [comment]
I'll defer to Justin on that. +1

**Comment by robertkowalski** [comment]
merged as 4627fea6adb59ed02d772e5964dca922514f7643

**Pull request closed without merging**
