### PR TITLE
tests: fix description for test

### PR DESCRIPTION
**Pull request by robertkowalski**
the test tests that the right api-url is returned (no relative
url for the app, but an absolute for the url)

### CODE REVIEW

**Comment by garrensmith** [comment]
That looks better, this test will fail if you run it on its own. You need to include `'addons/documents/base'` in the require list.

**Comment by robertkowalski** [comment]
i see, should be fixed now

**Comment by garrensmith** [comment]
+1

**Comment by robertkowalski** [comment]
merged as f199df6d9b0c9f61675160e6a8c47abe40a66833 and 2ab01436a1f47773a96fe6c9a1b80fb003c85fe7

**Pull request closed without merging**
