### PR TITLE
Remove raf

### PR DESCRIPTION
**Pull request by robertkowalski**
Garren and me tried to use the latest layoutmanager in summer
2014 - the experiment lead to performance improvements regarding
the rendering of our application, but we had to disable it as we
as it lead to timing issues.

As we are moving to React it does not make sense to me to invest
further time into the issues we had in summer.

This commit removes the leftovers of the experiment that are not
needed any more and cleans up.

See apache#29

### CODE REVIEW

**Comment by benkeen** [comment]
+1

**Comment by michellephung** [comment]
+1

**Comment by garrensmith** [comment]
This fix needs to be applied to get the tests working

```diff
diff --git a/app/addons/documents/tests/nightwatch/bulkDelete.js b/app/addons/documents/tests/nightwatch/bulkDelete.js
index aeb1651..bc43ba9 100644
--- a/app/addons/documents/tests/nightwatch/bulkDelete.js
+++ b/app/addons/documents/tests/nightwatch/bulkDelete.js
@@ -59,7 +59,7 @@ module.exports = {
       .click('#next')
       .waitForElementVisible('[data-id="27"]', waitTime, false)
       .click('#previous')
-      .waitForElementPresent('.control-select-all.js-headerbar-togglebutton-selected', waitTime, false)
+      .waitForElementPresent('.js-headerbar-togglebutton-selected', waitTime, false)
       .end();
   }
 };```

**Comment by garrensmith** [comment]
+1

**Comment by robertkowalski** [comment]
merged as 5752c486289ab75e7d6d282bff0c7130e45ab2ec and be661fb11f657700af2c524ff2626da680617698

**Pull request closed without merging**
