### PR TITLE
Fix couchapp_deploy

### PR DESCRIPTION
**Pull request by kxepal**

### CODE REVIEW

**Comment by kxepal** [comment]
@garrensmith @robertkowalski 
no problem if I merge this?

**Comment by garrensmith** [comment]
I will quickly test it tomorrow and let you know. 

All misspelling thanks to my iPhone

**Comment by garrensmith** [comment]
+1. Sorry for taking so long.

**Comment by kxepal** [comment]
Cool! No problems. Fauxton-as-couchapp seems not very popular nowdays anyway (:

**Pull request closed without merging**
