### PR TITLE
Pass the second param to beforeSend

### PR DESCRIPTION
**Pull request by rnewson**
I forgot to send this argument on which broke attachment uploading

COUCHDB-2762

### CODE REVIEW

**Comment by robertkowalski** [comment]
every pr needs a test, i would suggest an integration test to avoid regressions in the future for this feature. example test: https://github.com/apache/couchdb-fauxton/blob/master/app/addons/documents/tests/nightwatch/createsDocument.js

**Comment by rnewson** [comment]
Will you fix the test suite first?

**Comment by rnewson** [comment]
merged. now let's fix the tests. given the errors are completely opaque, I don't even know where to start.

**Comment by robertkowalski** [comment]
maybe we should avoid merging red builds in the future as a start. 

as i said two days ago, i am happy to help next week.

**Comment by robertkowalski** [comment]
when running the test locally (with `grunt nightwatch --file=createsDatabase`) i get:

```
2015-08-07 23:08:38.335 [warning] node1@127.0.0.1 <0.3783.0> write quorum (2) failed for updated:_dbs
2015-08-07 23:08:38.739 [debug] node1@127.0.0.1 <0.3510.0> httpd 403 error response:
 {"error":"forbidden","reason":"CSRF Cookie/Header mismatch"}

```

**Comment by robertkowalski** [comment]
it breaks as the tests are not designed for it. you can recreate the issue with 

1. creating a database and document in fauxton
2. open http://localhost:8000/_all_docs which proxies to _all_docs

**Comment by robertkowalski** [comment]
https://github.com/apache/couchdb-fauxton/pull/494

**Pull request merged**
