### PR TITLE
update ace@20.12.14

### PR DESCRIPTION
**Pull request by robertkowalski**
Fixes a freezing IE

src: https://github.com/ajaxorg/ace-builds @
     a4e495d8901876c6bafe3870a35cb8e32c827e97

### CODE REVIEW

**Comment by robertkowalski** [comment]
@benkeen was the editor theme altered on initial check in?

after the update:

bildschirmfoto 2015-02-23 um 18 04 38

**Comment by benkeen** [comment]
Possibly. Investigating.

**Comment by benkeen** [comment]
Do we want to include all theme files in assets/js/libs/ace? Right now we just include the one that we need: `theme-idle_fingers.js`

**Comment by benkeen** [comment]
Thanks for catching this, Robert. I've moved all the theme style overrides into our own `codeeditor.less` file, where they belong.

**Comment by garrensmith** [comment]
+1

**Comment by robertkowalski** [comment]
merged as 2222dcdd5eea062d0e5081b9adcd37757e0776ed and 067b0880da676c5bee7886d6994f07eb4c09216e

**Pull request closed without merging**
