### PR TITLE
Add / Use Redux

### PR DESCRIPTION
**Pull request by robertkowalski**
Here is my latest Redux work. It integrates Redux into Fauxton and gets rid of the old Backbone.js Models for the Permissions section.

Highlights:

 - Redux
 - Bluebird for Promises (goodbye jQuery deferreds)
 - Jest Testing
 - WHATWG fetch API
 - 1 file per component
 - Goodbye Backbone Collections and Models

### CODE REVIEW

**Comment by garrensmith** [comment]
Wow this is great. I really like it. Do you think you could add a nightwatch test for this?

**Comment by robertkowalski** [comment]
@garrensmith added the Selenium test

**Comment by robertkowalski** [comment]
got a second thumbs up from garren via chat

**Comment by robertkowalski** [comment]
merged!

**Pull request closed without merging**
