### PR TITLE
fix fauxton server for module

### PR DESCRIPTION
**Pull request by robertkowalski**
- use native node methods instead of custom solutions

### CODE REVIEW

**Comment by benkeen** [comment]
+1. 

Just a thought: might be worth noting in the doc somewhere that we need a recent(ish) version of Node. Couple of people have run into issues running a pre-ES6 version where it complains about `const`.

**Comment by robertkowalski** [comment]
@benkeen i decided to create a executable documentation which will notice the users even if they don't read the docs or know where they are located.

**Comment by benkeen** [comment]
Nice, love it!

**Comment by robertkowalski** [comment]
merged as 16a81431a89f2dbc5886855013c0b2bcb3acff72

**Pull request closed without merging**
