### PR TITLE
Added Fauxton noscript element

### PR DESCRIPTION
**Pull request by anio**
- CSS are inline because of noscript state.
  - Added `vim` temp file to gitignore too.

Closes COUCHDB-3056

### CODE REVIEW

**Comment by garrensmith** [comment]
@anio thanks for this, this is great. And very useful. 

Could you remove the changes to the `.gitignore` file. I think those are best kept in your own personal global gitignore file. 

After that I can merge this in.

**Comment by anio** [comment]
Hi,
OK, thanks!

**Comment by garrensmith** [comment]
Awesome thank you @anio. I have merged this into master. Could you close this PR for me.

**Comment by anio** [comment]
OK,
Thank you @garrensmith!

**Pull request closed without merging**
