### PR TITLE
Fixing view bugs

### PR DESCRIPTION
**Pull request by benkeen**
This is a continuation of Garren's ticket: https://github.com/apache/couchdb-fauxton/pull/391

### CODE REVIEW

**Comment by benkeen** [comment]
Bug: entering new lines within index field doesn't expand the Ace region. If you click outside, it resizes. When you click back in after that and enter/remove lines, it works fine.

**Comment by michellephung** [comment]
+1 it works for me

**Comment by benkeen** [comment]
@robertkowalski - I think this is pretty good now. I'll need to sort out the commit log, but other than that I think it's good to merge.

**Comment by benkeen** [comment]
This has been de-borked in this PR: https://github.com/apache/couchdb-fauxton/pull/402 - Closing.

**Pull request closed without merging**
