### PR TITLE
tabs: minor style updates

### PR DESCRIPTION
**Pull request by robertkowalski**
- make font for selected tab bold
 - don't highlight tab content on hover if tab is selected
 - inccrease space between tabs to 5px

### CODE REVIEW

**Comment by michellephung** [comment]
- the search bar in active tasks menu needs a list-style: none; on the list item.

**Comment by michellephung** [comment]
+1 otherwise

**Comment by robertkowalski** [comment]
@michellephung it got that, with `.component-tab-list-element` ?

**Comment by michellephung** [comment]
yes

**Comment by robertkowalski** [comment]
merged!

**Comment by michellephung** [comment]
i think you can add .component-tab-element

**Pull request closed without merging**
