### PR TITLE
Create required database beforeEach tests

### PR DESCRIPTION
**Pull request by popojargo**
## Overview

Creates the required database for the new docker image: `_users, _replicator, _global_changes`

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by popojargo** [comment]
@wohali Here's the fix. I had a local error unrelated to this change. I will wait for travis to run and fix if it still occurs

**Comment by wohali** [comment]
@popojargo will this error out if the DB already exists? It should tolerate a 412.

**Comment by popojargo** [comment]
@wohali It does check the error message. but I will check if I can access the status code from the exception.

**Comment by popojargo** [comment]
Its greeeen @wohali

**Pull request merged**
