### PR TITLE
[DISCUSSION] enable include_docs per default

### PR DESCRIPTION
**Pull request by robertkowalski**
- shows document content
- do not override the amount of displayed docs and set it to 100
  when clicking back

### CODE REVIEW

**Comment by kxepal** [comment]
That was so long time ago initially. The problem is that indexes pages view turns into nightmare when you deal with big documents since you cannot disable this option before actual request is made. 

Imagine 4MiB documents in db. 100 per page (default) -> 400MiB of received JSON which need to parse and render. Default options shouldn't hurt users in any situations.

**Comment by michellephung** [comment]
:/  maybe test for how big a document is before showing it?

**Comment by kxepal** [comment]
@michellephung Good idea, and it's possible with additional HEAD request per document. 100 rows per page - 100 additional requests, but do we really need that?

**Comment by michellephung** [comment]
no that wouldn't be good

**Comment by elistevens** [comment]
I would like to have it in the user's hands, off by default.  Sometimes I'm going to want to see 400mb of JSON, but it will be rare.

**Comment by willholley** [comment]
how about off by default but remembering the setting between visits to the page (could be per-database / view)? The large documents problem happens regardless of when the user uses include_docs so it sounds like a separate ticket / fix.

**Comment by robertkowalski** [comment]
We are planning table views, see also the data importer that is about to land

**Comment by garrensmith** [comment]
This will be fixed when we switch to a more default table view.

**Pull request closed without merging**
