### PR TITLE
Nightwatch auth moved to separate folder

### PR DESCRIPTION
**Pull request by benkeen**
This has been done to allow overriding, simply by specifying a
different location for the folder in the settings.json file.

### CODE REVIEW

**Comment by benkeen** [comment]
The failing zeroclipboard failing test is unrelated.

**Comment by robertkowalski** [comment]
Ok, how do we proceed? Maybe we should try to make the test more stable to make live easier for everyone?

**Comment by benkeen** [comment]
Yes, obviously the test needs to be fixed. We can either merge this now or wait for that test to be fixed - either is fine. I've had zero time to look at it this week, but I can look next.

**Comment by garrensmith** [comment]
+1. I'm ok with this being merged in. I think the test failure is unrelated and this is useful.

**Comment by benkeen** [comment]
Thanks Garren. Merged as f9b0ee0.

**Pull request closed without merging**
