### PR TITLE
remove sidebar class and set sidebar width in #sidebar-content

### PR DESCRIPTION
**Pull request by garrensmith**
Without this fix the sidebar goes across into the main section like this:

### CODE REVIEW

**Comment by robertkowalski** [comment]
that fixes the issue, but we have to take care of 

```css
.sidebar .polling-interval {
```

in `activetasks.less`

**Comment by robertkowalski** [comment]
example fix

```patch
diff --git a/app/addons/activetasks/assets/less/activetasks.less b/app/addons/activetasks/assets/less/activetasks.less
index 5acc4bb..68c44a9 100644
--- a/app/addons/activetasks/assets/less/activetasks.less
+++ b/app/addons/activetasks/assets/less/activetasks.less
@@ -45,7 +45,7 @@
   }
 }

-.sidebar .polling-interval {
+.nav.polling-interval {
   li.nav-header {
     padding: 9px 0px 0px 9px;
   }
```

**Comment by robertkowalski** [comment]
+1

**Comment by garrensmith** [comment]
merged.

**Pull request closed without merging**
