### PR TITLE
Fix Replication urls

### PR DESCRIPTION
**Pull request by popojargo**
## Overview

Fixed the url for replication

## Testing recommendations

1. Login in Fauxton
2. Click on a database
3. At the top left side bar, click on the three dots to the right of the database name (ViewTabsSideBar).
4. Click on `Replicate Database`
5. It should route to the replication view.

## GitHub issue number

#1007 

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by popojargo** [comment]
@garrensmith  or @Antonio-Maranhao , I have fixed the url for the database replication but if I want to provide tests, what should I do (or is it necessary)?

**Comment by Antonio-Maranhao** [comment]
@popojargo thanks for the pull request. I think a nightwatch test for that dropdown menu is probably the best approach here. 
Here's an example that you can follow: https://github.com/apache/couchdb-fauxton/blob/master/app/addons/documents/tests/nightwatch/deleteDatabaseModal.js#L50

**Comment by popojargo** [comment]
Indeed, I did a nightwatch test for another pr and it seems appropriate. I will a test tonight

**Comment by garrensmith** [comment]
@popojargo just for future reference. Rather don't merge master changes into your PR branch. Rather do a PR. It keeps the branch a little neater.

**Comment by popojargo** [comment]
@garrensmith  What do you mean? I should create a branch from the upstream instead of syncing my master and branching?

**Pull request merged**
