### PR TITLE
Fixing view bugs

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by benkeen** [comment]
This has been de-borked in this PR: https://github.com/apache/couchdb-fauxton/pull/402 - Closing.

**Comment by garrensmith** [comment]
+1 looks good to me. Nice work

**Comment by benkeen** [comment]
Looks good, Robert. +1

**Comment by robertkowalski** [comment]
merged as 54b118562813113d3ee93244ab8c41da01123e47

**Pull request closed without merging**
