### PR TITLE
Fire event when navbar size changes

### PR DESCRIPTION
**Pull request by garrensmith**

### CODE REVIEW

**Comment by garrensmith** [comment]
This also fixes https://issues.apache.org/jira/browse/COUCHDB-2555

**Comment by robertkowalski** [comment]
I could not find out what it fixes exactly - both the commit message and the linked ticket does not describe what behaviour exactly is currently wrong (e.g. how can i see the bug) and which behaviour is expected

**Comment by robertkowalski** [comment]
+1

**Comment by benkeen** [comment]
+1

**Pull request merged**
