### PR TITLE
Support editing _local docs

### PR DESCRIPTION
**Pull request by SCdF**
## Overview

Adds support for editing `_local` docs in Fauxton.

## Testing recommendations

To test, create a _local doc and then modify the Fauxton URL to see the edit page:

## GitHub issue number

Fixes apache/couchdb-fauxton#978

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by SCdF** [comment]
NB: I couldn't work out which test to change to add a test for this. Direction here would be appreciated.

**Comment by garrensmith** [comment]
Hi Stefan, take a look at the nightwatch tests found under each test/nightwatch folder in the documents folder. There should be some examples there you can build off of

All misspelling thanks to my iPhone.
________________________________

**Comment by garrensmith** [comment]
@SCdF You can copy this test https://github.com/apache/couchdb-fauxton/blob/master/app/addons/documents/tests/nightwatch/createsDocument.js#L16-L59

**Comment by SCdF** [comment]
@garrensmith cheers for pointing me in the right direction! I've created a test like the one you linked me but for local docs.

**Comment by SCdF** [comment]
@garrensmith I had to fix one eslint error, but we're good to go now 👍

**Comment by garrensmith** [comment]
@SCdF looks good. I'll merge soon as the tests have run with the update from master

**Comment by garrensmith** [comment]
@SCdF thanks so much for the contribution.

**Pull request merged**
