### PR TITLE
unify jshint and jscs

### PR DESCRIPTION
**Pull request by robertkowalski**
use the modern eslint to replace jshint and jscs

pros:

 - faster checks and boot of the devserver as everything is done in one run
 - style testing for jsx files

this prepares react 14 and babel, together with a refactor of the Gruntfile and buildsystem :)

### CODE REVIEW

**Comment by robertkowalski** [comment]
note: we test a few more files now and our jsx is now tested, too so i had to make a few style fixes.

**Comment by robertkowalski** [comment]
note: run npm install to install eslint

**Comment by benkeen** [comment]
+1 great work! No problems at all, and it's nice and zippy now.

**Comment by robertkowalski** [comment]
merged as:

42b9fa4069e5fa17df61c2feea171bf3657642d3
d2d98bd9a9d3ea355daaa386270eec5adb210e1e
1d8569f126e1f1818b3d6bc868f7ff53fe771111
3e86afa138ec54c942f64a281d6001bde324a200
44a476fc5ce8aef55460849a323425c6c15e8fe1
901d0060f7c1acff0b1b9cec50da4b6c157a36b1

**Pull request closed without merging**
