### PR TITLE
Fix - Create replication fails when db doesn't exist

### PR DESCRIPTION
**Pull request by Antonio-Maranhao**
## Overview

The `_replicator` db was not being automatically created when a new replication is created.

The test was also fixed because it was failing for this scenario.

## Testing recommendations

- Delete `_replicator` db
- Create a new replication
- Operation succeeds

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by popojargo** [comment]
Question: Why should it be the responsability of Fauxton to create the database? Usually when you setup your Couch, it should automatically create the databases. I don't think we can't just add the _replicator database and omit the _users and other system databases.

As for Fauxton dev environment, we switched to docker recently which force use to create system databases manually. Maybe you just want to tweak this instead?

**Comment by rnewson** [comment]
This PR mixes substantive changes with cosmetic (whitespace) ones. Can you update to remove the latter and rebase it to remove the merge from master too pls.

**Comment by rnewson** [comment]
I'm +1 on the intention of the patch but I can't verify that your change is the right way to do it.

**Comment by popojargo** [comment]
What's the reason for closing this? @Antonio-Maranhao

**Comment by Antonio-Maranhao** [comment]
@popojargo sorry, my brain must have short-circuited. I meant to merge, not close it.

**Pull request merged**
