### PR TITLE
Upgrade JQuery (with sidebar fixes)

### PR DESCRIPTION
**Pull request by Antonio-Maranhao**
## Overview

Upgrades to jquery 3 and removes bootstrap.js since we now use react-bootstrap

Includes all changes from #982 plus fixes to sidebar

### CODE REVIEW

**Comment by Antonio-Maranhao** [comment]
@garrensmith could you please review? Cheers.

**Comment by garrensmith** [comment]
@Antonio-Maranhao I've picking up an issue. If I click on the spanner icon for a view and then click edit it does nothing. This only seems to happen with a db with a `/` in it.

**Comment by garrensmith** [comment]
Also could you rebase this with master

**Comment by Antonio-Maranhao** [comment]
Replaced with #994

**Pull request closed without merging**
