### PR TITLE
Show total amount of databases on server

### PR DESCRIPTION
**Pull request by michaelwheeler**
Closes COUCHDB-2105

### CODE REVIEW

**Comment by garrensmith** [comment]
thanks @michaelwheeler, sorry for teh slow response. I'll try and take a look at this today.

**Comment by garrensmith** [comment]
Merged. Thanks @michaelwheeler for this. This is great.

**Comment by garrensmith** [comment]
Can you close this PR. Its merged to master.

**Comment by michaelwheeler** [comment]
Sure thing, thanks!

**Pull request closed without merging**
