### PR TITLE
Added sidebar to permissions page

### PR DESCRIPTION
**Pull request by benkeen**
To see the change, select a database and click on the Permissions page. You'll see the sidebar there now, like all the other pages within Databases.

The code changes are in the first commit. Whitespace/styles fixes in the second.

### CODE REVIEW

**Comment by garrensmith** [comment]
@benkeen this doesn't quite work. If I click on the permissions page, all the design docs listed in the sidebar disappear.

**Comment by benkeen** [comment]
Ack! Thanks for spotting that @garrensmith, I'll take a look.

**Comment by benkeen** [comment]
All fixed, thanks @garrensmith.

N.B. Now the sidebar consistently shows up, I think I'll create a follow up ticket to retain the hide/show state of the sidebar as you go from page to page.

**Comment by michellephung** [comment]
+1 looks good to me

**Comment by benkeen** [comment]
Thanks @michellephung! I just made a small change; I'll merge once the light goes green.

**Comment by benkeen** [comment]
Merged as aae7b7c

**Pull request merged**
