### PR TITLE
React index editor

### PR DESCRIPTION
**Pull request by garrensmith**
This is part two of #216. This is the index editor. This required #233 to land first.

### CODE REVIEW

**Comment by robertkowalski** [comment]
hi garren can you rebase?

**Comment by garrensmith** [comment]
@robertkowalski @benkeen @michellephung this has been rebased. I would appreciate it if you could take another look.

**Comment by robertkowalski** [comment]
i found a small issue when using the editor: https://cloudup.com/cpHQFd-zrAz

**Comment by robertkowalski** [comment]
hi garren i found some small things, the branch looks already really really great!

**Comment by benkeen** [comment]
The code looks totally wicked.

Minor stuff:
- the Edit Index tab should have cursor:pointer
- comparing the Edit Index tab with other tabs (say Changes > Filter) it’s not quite the same. That one has a mouseover state (red) and is grey by default unless clicked. Not sure what @seanbarclay wants.
- I don't suppose "Edit Index" could read "Edit View" instead? It’s listed under Views in the sidebar, and the delete alert() says “do you want to delete this View?”. I've always found the duplicate terms confusing - now I realize index === view.
- there should be more space after the end of the following labels + the “?” icon: “Save to Design Document", “Map function”

Probably unrelated:
- after logging in and going to the Database page I got a blank, disabled page nav << 1 >> at the bottom right, even though there’s only a single page. Shouldn’t that be omitted if there’s only one page?

**Comment by michellephung** [comment]
everything looks okay Garren,
the only thing i was going to say is the space between the circle question marks, which ben already mentioned. 

@benkeen the disable page nav on one page is happening on the live site too. I'll make a ticket for it. I think I saw it being disabled before.

**Comment by garrensmith** [comment]
thanks @benkeen and @michellephung. I've made some of those fixes.

**Comment by robertkowalski** [comment]
Seems we lost the compact view button:

bildschirmfoto 2015-01-27 um 16 36 13

**Comment by robertkowalski** [comment]
currently just the reduce editor has a button for beautifying the code

**Comment by robertkowalski** [comment]
discussed the topic with garren, there will be follow up tickets as the both are currently broken on master, too

+1

**Comment by garrensmith** [comment]
Merged :rocket:

**Pull request closed without merging**
