### PR TITLE
allow custom csp header

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by benkeen** [comment]
Code is fine. Could I get some pointers on how to test this?

**Comment by robertkowalski** [comment]
in your settings.default.json, add this to couchserver above couchconfig:

 "contentSecurityPolicyHeader": "default-src 'self'; img-src 'self' font-src 'self'; script-src 'self' style-src 'self';",

and you should get csp errors in the console as they are stricter than our default rules.

```diff
diff --git a/settings.json.default b/settings.json.default
index b44c98b..d34ad79 100644
--- a/settings.json.default
+++ b/settings.json.default
@@ -61,7 +61,15 @@
         }
       }
     },
-
+    "couchserver": {
+      "dist": "./dist/debug/",
+      "port": 8000,
+      "contentSecurityPolicy": true,
+      "contentSecurityPolicyHeader": "default-src 'self'; img-src 'self' font-src 'self'; script-src 'self' style-src 'self';",
+      "proxy": {
+        "target": "http://localhost:5984"
+      }
+    },
     "couch_config": {
       "fauxton": {
         "db": "http://localhost:5984/fauxton",
```

**Comment by benkeen** [comment]
Looks good, thanks @robertkowalski! +1

**Comment by robertkowalski** [comment]
merged as 1c8d86e75e32a36d98c627f7886d125a12693ac0

**Pull request closed without merging**
