### PR TITLE
Replace notification bar by notification toasts

### PR DESCRIPTION
**Pull request by popojargo**
## Overview

Replace the existing notification bar by toasts. It takes less place on the UI and it's less distracting. 

### Testing the clear feature: 
1. Try to create a database with an invalid name (eg: !"/!"/)
2. The info should appear and slowly disappear after the error shows up

### Testing the keyboard shortcut:
Pressing "ESC" when a toast is shown should instantly remove it.

### Testing toast hover
By default, toast are a bit transparent. When you hover it, it should be fully opaque.

## GitHub issue number

#1262 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by popojargo** [comment]
Will update once #1266  will be merged

**Comment by Antonio-Maranhao** [comment]
@popojargo you're definitely on the right track here - I love the ESC to dismiss it !!!
I find the colored background doesn't really match the rest of Fauxton's design. I'd prefer something closer to the original notification bar:

image

which you can get with: 
```
.Toastify__toast--info {
  &, .Toastify__close-button--info {
    border: 1px solid #999;
    border-left: 6px solid @infoAlertBackground;
    border-right: 0;
    background-color: #f1f1f1;
    color: black;
  }
}
```

Also, my preference is for `opacity: 1` always (i.e. no transparency), otherwise it's harder read the notification text when the background already has some text/elements. E.g.:

image


image

**Comment by Antonio-Maranhao** [comment]
@popojargo oh.... and thanks for all the fixes/PRs :)

**Comment by wohali** [comment]
I don't have an easy way to test this myself, so I'll just go on what others have said + the images submitted previously.

First, Thanks for not having the new element overlay the toolbar at the top! This was my biggest complaint about the old notifications.

For now please match the old colours in this PR. We can have a separate bike-shed PR to refresh the visual design and bring in other contributors who have helped in the past on this.

I also agree with Antonio: drop the transparency, opaque is best here.

**Comment by popojargo** [comment]
I've used a white for the toasts background so it stands out a bit more. I've also moved the toast completely to the right but kept the vertical space with the app bar.

https://share.getcloudapp.com/eDu6PeQK

**Comment by popojargo** [comment]
@wohali Mind to rerun Travis please ? :)

**Comment by wohali** [comment]
@popojargo you can do it yourself - click on Details, go to Travis, log in to Travis using your GH creds, then restart the build... sorry am running out the door, back in 2 hours

**Comment by wohali** [comment]
@popojargo Hey, this (and #1271) are blocking CouchDB 3.0.1/3.1.0 - it's the very last thing to go in before release, everything else is ready to go. Do you have time to help with this today?

**Comment by popojargo** [comment]
@wohali Fixing the "flaky" tests since this morning. Should be done by the end of the day

**Comment by popojargo** [comment]
@wohali Something is going wrong on 2.3.1 but I can't reproduce that locally. Can we merge that and I'll keep working on the E2E tests to make them more robust?

**Comment by wohali** [comment]
@popojargo I can't merge unless the tests pass.

You can disable the CI check in `.travis.yml` against 2.3.1 for now if you want, but we'll need to fix Fauxton for 2.x if we intend to do any patch releases (2.3.2, 2.3.3, etc.)

**Comment by popojargo** [comment]
@wohali I'll keep digging

**Comment by wohali** [comment]
Looks like it's passing and you have a +1.... merge it! :)

**Pull request merged**
