### PR TITLE
Display view error if view is broken

### PR DESCRIPTION
**Pull request by garrensmith**
If a user saves a view that doesn't work the error will be displayed on
to the user and the page will load.

This fixes COUCHDB-2646

### CODE REVIEW

**Comment by garrensmith** [comment]
Here is the actual fix https://github.com/apache/couchdb-fauxton/pull/334/files#diff-308dc0fc971fc5a587b9f81bb7a94d1eR369

The rest is linter stuff.

**Comment by kxepal** [comment]
May be separate the actual fix and linter stuff into two commits?

**Comment by garrensmith** [comment]
@robertkowalski and @kxepal I've clean up this PR.

**Comment by robertkowalski** [comment]
+1 thank you!

**Comment by kxepal** [comment]
+1 !

**Comment by garrensmith** [comment]
Merged.

**Pull request closed without merging**
