### PR TITLE
Couchdb 3224

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by sergey-safarov** [comment]
@robertkowalski could you also look to case when file attachments can not be downloaded when database see contains "/" symbols.

**Comment by sergey-safarov** [comment]
Hello @robertkowalski 
I found that when edited document in database with "/" symbols in name and pressed "Save Changes" button, then list of database documents is not displayed.

**Comment by sergey-safarov** [comment]
Hello @robertkowalski 
Please look at commit 655d775fd81e915fc66fa345c359c3ed62236e81 in PR 802
https://github.com/apache/couchdb-fauxton/pull/802/commits/655d775fd81e915fc66fa345c359c3ed62236e81

**Comment by garrensmith** [comment]
I think most of these have been merged in.

**Pull request closed without merging**
