### PR TITLE
encodeding url path for database name with special characters

### PR DESCRIPTION
**Pull request by timmak**
Should resolve https://issues.apache.org/jira/browse/COUCHDB-3146

### CODE REVIEW

**Comment by timmak** [comment]
test pass locally running ci steps if some can point in the right direction to fixing them, I will get right on it.

**Comment by michellephung** [comment]
Hi Tim, thanks for the pr! For the last commit (2da978d), it looks like fauxton didn't get started on travis, which happens sometimes. Try restarting the travis tests again. Usually I'll add a space somewhere, commit it, then see if the tests pass. If they pass, I'll delete the extra space introduced, commit it, then squash all the things

**Comment by michellephung** [comment]
For the second commit (3940f71) it looks like it also hiccups on the documentation links, which i wrote. I have to set up docker and the test suites again since my setup has changed a bit. I can look into it if you give me a few days

**Comment by timmak** [comment]
@michellephung everything fixed now

**Comment by robertkowalski** [comment]
+1

**Comment by robertkowalski** [comment]
merged as e53deb5d90fa7d6751bb753415dda5274a2b2cb5 and 1aa4ca6f34a718c294a06a1301f39fe05f157a1c

thank you!

**Comment by robertkowalski** [comment]
you can close the PR now

**Pull request closed without merging**
