### PR TITLE
fix url for resources

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by benkeen** [comment]
Looks pretty solid... two things (second looks unrelated):

**Permissions page:**
- trying to add anything through the fields shows an error: “Could not update permissions - reason: Updates to security docs are disabled during security migration.”. Deleting, too. 

**Documents:**
- possibly unrelated, but uploading a file to an existing doc results in a “$form.clearForm is not a function” error.

**Comment by robertkowalski** [comment]
permissions error is a dbcore issue, it also happens on master

**Comment by benkeen** [comment]
Thanks @robertkowalski. +1

I'll fix issue 2 in a sec.

**Comment by robertkowalski** [comment]
awesome thx!

**Pull request closed without merging**
