### PR TITLE
Fix View Attachments menu and upload modal in doc editor

### PR DESCRIPTION
**Pull request by Antonio-Maranhao**
## Overview

In the document editor: 
- Fixes "View Attachments" dropdown menu that stopped working after removal of `bootstrap.js` in https://github.com/apache/couchdb-fauxton/pull/994
- Fixes the file upload modal that was not displaying error messages.

## Testing recommendations

- Click on a document to bring up the editor
- Click on 'Upload Attachment'
   - Choose a file that starts with underscore (e.g. '_afile.txt') then click 'Upload Attachment'
   - The modal should show the error message: `Attachment name '_afile.txt' starts with prohibited character '_'`
   - Pick another file then click 'Upload Attachment'
   - Success message is displayed
   - 'View Attachements' is now visible. Click on it and select the file to download it.

### CODE REVIEW

**Comment by Antonio-Maranhao** [comment]
@garrensmith can you please review? thanks!

**Comment by chegeiser** [comment]
I've made the edits in my deployment to actions.js and to components.js but it I still have the problem of not being able to view the attachements (jpg) in Fauxton. I did notice that action.js line 217 deletes a few of items leaving the line as <error: resp..reason> - I assume this should actually be <error: resp.reason> - I've tried both ways and after restarting CouchDB neither way enables attachment viewing. Any ideas how to fix this, or why the problem remains?
Thank you,
Che

**Comment by popojargo** [comment]
Have you tried with the latest version?

**Comment by chegeiser** [comment]
I pulled the actions.js and components.js files and put them in too my installation of CDB 2.1.1 - no luck. I next grabbed the latest copy of CDB from here: https://www.apache.org/dyn/closer.lua?path=/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz using the link here: http://mirrors.sorengard.com/apache/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz

Still have the same problem.

**Pull request merged**
