### PR TITLE
tests: move tests to subcomponents

### PR DESCRIPTION
**Pull request by robertkowalski**
some subcomponents already have this, this removes the remaining
tests to their subcomponents

### CODE REVIEW

**Comment by michellephung** [comment]
+1

**Comment by benkeen** [comment]
Oh nice, good change @robertkowalski.

**Comment by benkeen** [comment]
+1

**Comment by robertkowalski** [comment]
merged as deaf53c9f60ea9047eb203c9d60b3a7cd6d5b1f0

**Pull request closed without merging**
