### PR TITLE
Fix for doc typeahead field being hidden

### PR DESCRIPTION
**Pull request by benkeen**
When typing a doc name in the Doc ID field on the Database -> All
Docs page, it would get cut off. This PR ensures it overlaps
the body content.

Not thrilled with the extra `<span>` needed, but the position:relative 
high up in the tree caused issues, and this at least localizes the 
position:relative to the search icon.

### CODE REVIEW

**Comment by michellephung** [comment]
+1

**Comment by benkeen** [comment]
Thanks for your help on this, Michelle! Just re-running one more time....

**Comment by michellephung** [comment]
:D

**Comment by robertkowalski** [comment]
hi ben,

i think that is not fixing the issue: https://cloudup.com/cZrYuRUH4lP

**Comment by robertkowalski** [comment]
fun fact: it seems to work if you have visited the documents page before and don't start at the databases page

**Comment by benkeen** [comment]
That's actually a different issue. I just fixed an issue on the database -> documents page. I think I know the cause of this, but it's an old bug.

**Pull request merged**
