### PR TITLE
Don't redirect on dismissing the notification

### PR DESCRIPTION
**Pull request by robertkowalski**
If you edited a document and then clicked on cancel, you were
redirected to the database list

closes COUCHDB-2550

### CODE REVIEW

**Comment by garrensmith** [comment]
I've getting a 'Uncaught TypeError: Cannot read property 'preventDefault' of undefined' in the console. This happens if I click on the 'x' then wait 1 second or so then the error appears in the console.

**Comment by robertkowalski** [comment]
ugh, monday morning... should be fixed now, @garrensmith

**Comment by garrensmith** [comment]
+1 working nicely

**Comment by robertkowalski** [comment]
green test, @benkeen mind taking a look on my attempt to fix the flaky test?  f25b52d i run it approx. 10 times and it stayed green.

if the code looks nice for you i would merge. i'll put that test on my list, if it stays flaky i will have to come up with another approach.

**Comment by benkeen** [comment]
Sure, no problem! I'll look at it shortly.

**Comment by benkeen** [comment]
+1 this looks good Robert. Ran 10 times locally, all turning up green.

**Comment by robertkowalski** [comment]
merged as b872ebfa4adfc2c8a9d0643150d3404f9713ab0e and 17cfa631c1dde186f06cd1eff61552746e9ae931

**Pull request closed without merging**
