### PR TITLE
Fix production build

### PR DESCRIPTION
**Pull request by popojargo**
## Overview

Move a new devDependencies to production

## Testing recommendations

`npm install --production && ./node_modules/grunt-cli/bin/grunt couchdb` should build successfully

## GitHub issue number

#1079 

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

**Comment by popojargo** [comment]
@wohali I tried to build couchdb with the rebar.config.script pointing to a tag on my fork but it doesn't seems to resolve my tag.

I tried with: 

```
{fauxton,          {url, "https://github.com/popojargo/couchdb-fauxton"},
                   {tag, "v1.1.15"}, [raw]},
```

**Comment by michellephung** [comment]
i'm seeing this issue locally as well, even with apache/couchdb-faxuton v1.1.14

**Comment by michellephung** [comment]
i forgot to thank you for this. Thanks for getting a fix in so quickly :)

**Comment by popojargo** [comment]
You're welcome :smile:

**Pull request merged**
